# Generated by Django 3.0.4 on 2020-08-12 16:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(help_text='Course number : ', max_length=25, unique=True)),
                ('course_title', models.CharField(help_text='Course title : ', max_length=250)),
                ('credit_hour', models.FloatField(help_text='Credit hours : ')),
                ('course_type', models.IntegerField(choices=[(1, 'Theory'), (2, 'Lab'), (3, 'Thesis')])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1)),
                ('with_batch', models.CharField(max_length=4)),
                ('comment', models.CharField(default='N/A', max_length=25)),
                ('cause_of_rejection', models.CharField(blank=True, max_length=500, null=True)),
                ('is_retake', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('school', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=25, unique=True)),
                ('batch', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='batch')),
                ('name', models.CharField(help_text='Name : ', max_length=100)),
                ('contact_number', models.CharField(help_text='Contact Number :', max_length=25)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline', models.ForeignKey(help_text='Discipline : ', on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline', models.ForeignKey(help_text='Select Discipline : ', on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline')),
                ('user', models.ForeignKey(help_text='User object for teacher', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThesisConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesis_type', models.IntegerField(choices=[(1, 'Duration 1 term, evaluation 1 term'), (2, 'Duration 2 terms, evaluation 1 term'), (3, 'duration 2 terms, evaluation 2 terms')], verbose_name='Thesis type')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Class Test'), (2, 'Semester Final')])),
                ('section', models.CharField(max_length=5)),
                ('class_test_no', models.IntegerField(blank=True, null=True)),
                ('obtained_marks', models.CharField(default='0', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.CourseRegistration')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TermData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('session', 'year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='TabulationStudentWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, '1st term'), (2, '2nd term'), (3, 'Special term')])),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('session', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Student', verbose_name='Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher', verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TabulationCourseWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, '1st term'), (2, '2nd term'), (3, 'Special term')])),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('session', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Course', verbose_name='Course')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher', verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SessionalAssessmentViva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, '1st term'), (2, '2nd term'), (3, 'Special term')])),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('session', models.CharField(default='', max_length=50)),
                ('no_student', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Course', verbose_name='Course')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
                ('teacher1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher1', to='tabulation.Teacher')),
                ('teacher2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher2', to='tabulation.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPreparationScriptExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, '1st term'), (2, '2nd term'), (3, 'Special term')])),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('session', models.CharField(default='', max_length=50)),
                ('no_question_t1', models.IntegerField(default=0)),
                ('no_question_t2', models.IntegerField(default=0)),
                ('no_script_t1', models.IntegerField(default=0)),
                ('no_script_t2', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Course', verbose_name='Course')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
                ('teacher1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher1', to='tabulation.Teacher')),
                ('teacher2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher2', to='tabulation.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDrawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, '1st term'), (2, '2nd term'), (3, 'Special term')])),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('session', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher', verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline')),
                ('main_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_course', to='tabulation.Course')),
                ('prerequisite_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_course', to='tabulation.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ModerationCommitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, '1st term'), (2, '2nd term'), (3, 'Special term')])),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('session', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher', verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='LabMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Sessional Assessment'), (2, 'Viva')])),
                ('obtained_marks', models.CharField(default='0', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.CourseRegistration')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Course'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Student'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.TermData'),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('student', models.ForeignKey(help_text='Student: ', on_delete=django.db.models.deletion.CASCADE, to='tabulation.Student')),
                ('teacher', models.ForeignKey(help_text='Teacher : ', on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher')),
                ('term', models.ForeignKey(help_text='Term : ', on_delete=django.db.models.deletion.CASCADE, to='tabulation.TermData')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, '1st term'), (2, '2nd term'), (3, 'Special term')])),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('session', models.CharField(default='', max_length=50)),
                ('no_question', models.IntegerField(default=0)),
                ('no_script', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Course', verbose_name='Course')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher', verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.CharField(default='0', max_length=100)),
                ('section', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'Both')])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.CourseRegistration')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerScriptScrutiny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, '1st term'), (2, '2nd term'), (3, 'Special term')])),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('session', models.CharField(default='', max_length=50)),
                ('no_script', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher', verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='OfferedCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Course')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.TermData')),
            ],
            options={
                'unique_together': {('course', 'discipline', 'term')},
            },
        ),
    ]
